grafeas:
  container:
    port: 8080
  service:
    port: 8080
  certificates:
    enabled: false
  endpoint: grafeas-server:8080

image:
  repository: quay.io/adewey/rode
  tag: "0.0.1"
  pullPolicy: Always

resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 100Mi
