# permissions to do viewer attesters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attester-viewer-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - attesters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - attesters/status
  verbs:
  - get
