# permissions to do edit collectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector-editor-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors/status
  verbs:
  - get
  - patch
  - update
