# permissions to do viewer collectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector-viewer-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors/status
  verbs:
  - get
