apiVersion: rode.liatr.io/v1alpha1
kind: Collector
metadata: 
  name: harbor-collector
  finalizers:
  - collectors.finalizers.rode.liatr.io
spec:
  harbor:
    harborUrl: "https://harbor.apps-crc.testing" # Protocol is required
    project: "adewey"
    secret: "rode/harbor-harbor-core" # Secret containing Harbor Admin credentials. Admin password must be stored in HARBOR_ADMIN_PASSWORD field.
  type: harbor
